version: "3.8"

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartHelp
    volumes:
      - ./pgdata:/var/lib/postgresql/data
